name: Bill clients

on:
  schedule:
    - cron: "0 12 29 * *"

jobs:
  bill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: "8.6.5"
          run_install: true
      - run: pnpm start
