name: Bill clients

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 29 * *"

jobs:
  bill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: pnpm
      - run: pnpm run start
